name: Check & fix styling

on:
  push:
    paths:
      - '**.php'
      - 'composer.lock'
      - 'pint.json'
      - '.github/workflows/pint.yml'

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run pint
        uses: whobutsb/laravel-pint-action@main
        with:
          preset: laravel

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
